# Determines whether the debug mode is enabled (prints error stacktraces in the console)
# You should only set this to 'true' if you have some problems you can't solve
debug-mode-enabled: false
 
# This is the ending of the messages file name that will be loaded
# ItemSlotMachine will attempt to load 'messages_<tag>.json'
# Built-in language tags are 'en-US' for English and 'de-DE' for German
language-tag: 'en-US'

# This section contains settings for designs
design:

  # This is the name pattern for designs that will be used for generating names
  # This string has to contain '{0}' as a placeholder for the generated id
  name-pattern: 'design{0}'
  
  # This section contains settings for the space check when building a slot machine
  # The space check will deny building if there is any block in the region of the design unless it is ignored
  space-check:
 
    # Determines whether the space check is enabled
    # If this is set to false building a slot machine will replace EVERY block
    enabled: true
  
    # This is a list of block types which are ignored by the space check
    ignored-types: ['snow', 'grass', 'fern', 'tall_grass', 'large_fern']
 
# This section contains settings for all slot machines
slot-machine:

  # This is the name pattern for slot machines that will be used for generating names
  # This string has to contain '{0}' as a placeholder for the generated id
  name-pattern: 'slot{0}'
  
  # This is the maximum amount of slot machines that can be used by the same player at a time
  # If this is set to a value lower than 1, the players will be able to use an unlimited number of slot machines
  use-limit: 1
 
# This section contains settings for the coin which is used to activate a slot machine
coin:
  
  # This is the item type that will be used as coin
  type: 'gold_nugget'
  
  # Determines whether a common item of the specified type can be used to activate a slot machine
  use-common-item: false
  
  # This is the price for a single coin
  price: 100.0